Repository arenadotio/ocaml-mssql, pull requests merged in 2020-05, with the labels that each got.

#36 Always consume all result sets in `execute`
  src/client.ml
  test/test_mssql.ml
Labels: size/S

#37 Skip non row result sets
  src/client.ml
  test/test_mssql.ml
Labels: size/M

#38 use upstream freetds
  Makefile
  dune
  freetds/.gitignore
  freetds/.travis.yml
  freetds/CHANGES.md
  freetds/LICENSE.md
  freetds/Makefile
  freetds/Makefile.in
  freetds/README.md
  freetds/appveyor.yml
  freetds/config/discover.ml
  freetds/config/dune
  freetds/dune-project
  freetds/examples/ct_example.ml
  freetds/examples/dbi_example.ml
  freetds/examples/dune
  freetds/freetds.opam
  freetds/scripts/debug
  freetds/scripts/ocamldebug
  freetds/scripts/toplevel
  freetds/src/ct.ml
  freetds/src/ct.mli
  freetds/src/ct_c.c
  freetds/src/dblib.cppo.ml
  freetds/src/dblib.mli
  freetds/src/dblib_stubs.c
  freetds/src/dune
  freetds/test/dune
  freetds/test/test_ct.ml
  freetds/test/test_dblib.ml
  mssql.opam
Labels: size/XXL

#39 generate opam file via dune
  .circleci/config.yml
  Makefile
  dune-project
  mssql.opam
  src/dune
Labels: size/L

#41 Reduce deps
  dune-project
  mssql.opam
  src/async_helper.ml
  src/client.ml
  src/client.mli
  src/db_field.ml
  src/db_field.mli
  src/dune
  src/row.ml
  src/row.mli
  src/test.ml
  src/test.mli
  test/dune
  test/test_mssql.ml
Labels: size/L

#42 Remove Mssql.Test
  src/mssql.ml
  src/test.ml
  src/test.mli
  test/test_mssql.ml
Labels: size/L

#40 Add CHANGES.md
  CHANGES.md
Labels: size/M

#43 Don't build tests for release
  test/dune
Labels: size/XS

#44 Opam improvements
  README.md
  dune-project
  mssql.opam
  test/test_mssql.ml
Labels: size/M

#45 README improvements
  README.md
Labels: size/S

#46 Add latest release badge to README
  README.md
Labels: size/XS

#48 Add v2.1.0 CHANGELOG
  CHANGES.md
Labels: size/S
